import {sellerMailToken} from './shipping-email.mjs';
const encode=text=>{let s='';for(const b of new TextEncoder().encode(text))s+=String.fromCharCode(b);return btoa(s);};
export async function sendCartEmail(env,order,type) {
  const token=await sellerMailToken(env),review=type==='review',q=order.quote,print=order.printJob;
  const seller=review||type==='print-seller'||type==='print-review'||type==='framing-seller';
  const subject=type==='framing-seller'?`Framing requested — hold original — ${order.id.slice(0,8)}`:review||type==='print-review'?'Art order needs review':type==='print-seller'?`Print sale — ${order.id.slice(0,8)}`:type==='print-shipped'?`Your prints have shipped — ${order.id.slice(0,8)}`:`Your Vermillion Aurora order ${order.id.slice(0,8)}`;
  const framed=q.items.filter(i=>i.framing);
  const framingNote=framed.length?`\n\nFRAMING REQUEST — NOT CHARGED\n${framed.map(i=>`${i.title}: ${i.framing.styleLabel} preference; ${i.framing.mat}. Framebridge estimate $${i.framing.estimate} before tax and upgrades. Delivery credit already paid: $${q.shipments.find(s=>s.slug===i.id)?.shipping||'0.00'}.`).join('\n')}\nTJ will confirm the frame, suitability, final price, and delivery timing by email before any framing is ordered. Framing is paid separately after approval. The delivery payment for each requested original will be credited toward its final delivery cost. These originals are held until you approve framing or choose unframed delivery; other items proceed normally.`:'';
  const lines=q.items.map(i=>`${i.title} · Quantity ${i.quantity} — $${(Number(i.amount)*i.quantity).toFixed(2)} USD${i.type==='print'?`\nImage ${i.imageSize.width} × ${i.imageSize.height} in; paper ${i.paperSize.width} × ${i.paperSize.height} in; ${i.paper}${i.mat?`; ${i.mat.name}, mat / frame ${i.mat.outer.width} × ${i.mat.outer.height} in`:""}${i.frame?`; ${i.frame.name} frame, ${i.frame.glazing.name} acrylic, assembled by FinerWorks`:""}`:''}`).join('\n');
  let body=review?`Order ${order.id}\n${order.reason}\nPayment: ${order.method}\nProvider reference: ${order.providerId||'Check by order ID'}\nDo not release inventory or ship until the payment is resolved.`:
    type==='framing-seller'?`A paid original order includes a framing request.\n\nOrder: ${order.id}\nBuyer: ${q.address.name}\nReply to: ${q.email}\nShip to: ${q.address.street1}, ${q.address.street2||''}, ${q.address.city}, ${q.address.state} ${q.address.zip}\n\n${lines}${framingNote}\n\nNEXT STEPS\n1. Contact the buyer to confirm the frame preference and mat. Verify the original's dimensions, medium, mounting, insurance, and current Framebridge quote.\n2. Send the buyer the final quote and delivery estimate, subtracting the saved delivery credit. Get approval and arrange payment separately. No framing amount has been collected in this checkout.\n3. Place the Framebridge mail-in order manually with the buyer's delivery address and mail the original using their instructions.\n4. Send the buyer confirmation and tracking. If they decline framing, confirm unframed delivery and arrange its label manually using the existing delivery payment.\n\nAutomatic Shippo labels are held only for the originals requesting framing. Do not send those originals to the buyer before their choice is confirmed. This email has not placed a Framebridge order.`:
    type==='print-review'?`Order ${order.id}\n${print.reason}\nPrint-lab reference: ${print.providerId||print.request.merchantReference}\nThe customer payment is recorded. Review the saved print job before submitting or refunding it.`:
    type==='print-shipped'?`Your fine-art prints have shipped.\n\nOrder ${order.id}\n${(print.shipments||[]).map(s=>`${s.carrier} ${s.service}\n${s.trackingNumber||'Tracking is not available for this shipment.'}\n${s.trackingUrl||''}`).join('\n\n')}\n\nPlease reply with any questions.\nTJ Murphy`:
    `${seller?'A print sale has been recorded. The print lab handles production and delivery.':'Thank you for collecting my work. Your payment is confirmed.'}\n\nOrder: ${order.id}\n${lines}\n\nArtwork: $${q.base}\nShipping: $${q.shipping}\nTax: $${q.tax}\nTotal paid: $${q.total} USD\n\nShip to:\n${q.address.name}\n${q.address.street1}\n${q.address.street2||''}\n${q.address.city}, ${q.address.state} ${q.address.zip}\n\n${print?'Prints ship from the print lab, separately from any originals. You will receive a shipment update.':'Originals are packed separately.'}${seller?`\nPrint-lab status: ${print.status}\nPrint-lab reference: ${print.providerId||print.request.merchantReference}\nQuoted production cost: $${print.quotedProductionCost}\nQuoted print shipping: $${print.quotedShipping}`:''}\nPlease reply with any questions.\n\nTJ Murphy\nhttps://vermillionaurora.com`;
  if(type==='confirmation')body+=framingNote;
  const mime=[`From: Vermillion Aurora <tj@vermillionaurora.com>`,`To: ${seller?'tj@vermillionaurora.com':q.email}`,
    `Subject: =?UTF-8?B?${encode((order.mode==='sandbox'?'[TEST] ':'')+subject)}?=`,`Message-ID: <cart-${order.id}-${type}@vermillionaurora.com>`,
    'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',encode(body)].join('\r\n');
  const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',signal:AbortSignal.timeout(20000),headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({raw:encode(mime).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')})});
  const result=await response.json();if(!response.ok||!result.id)throw Error('Order email needs review');return result.id;
}
