import {sellerMailToken} from './shipping-email.mjs';
const encode=text=>{let s='';for(const b of new TextEncoder().encode(text))s+=String.fromCharCode(b);return btoa(s);};
export async function sendCartEmail(env,order,type) {
  const token=await sellerMailToken(env),review=type==='review',q=order.quote,print=order.printJob;
  const seller=review||type==='print-seller'||type==='print-review';
  const subject=review||type==='print-review'?'Art order needs review':type==='print-seller'?`Print sale — ${order.id.slice(0,8)}`:type==='print-shipped'?`Your prints have shipped — ${order.id.slice(0,8)}`:`Your Vermillion Aurora order ${order.id.slice(0,8)}`;
  const lines=q.items.map(i=>`${i.title} · Quantity ${i.quantity} — $${(Number(i.amount)*i.quantity).toFixed(2)} USD${i.type==='print'?`\nImage ${i.imageSize.width} × ${i.imageSize.height} in; paper ${i.paperSize.width} × ${i.paperSize.height} in; ${i.paper}${i.mat?`; ${i.mat.name}, mat / frame ${i.mat.outer.width} × ${i.mat.outer.height} in`:""}`:''}`).join('\n');
  const body=review?`Order ${order.id}\n${order.reason}\nPayment: ${order.method}\nProvider reference: ${order.providerId||'Check by order ID'}\nDo not release inventory or ship until the payment is resolved.`:
    type==='print-review'?`Order ${order.id}\n${print.reason}\nProdigi reference: ${print.providerId||print.request.merchantReference}\nThe customer payment is recorded. Review the saved print job before submitting or refunding it.`:
    type==='print-shipped'?`Your fine-art prints have shipped.\n\nOrder ${order.id}\n${(print.shipments||[]).map(s=>`${s.carrier} ${s.service}\n${s.trackingNumber||'Tracking is not available for this shipment.'}\n${s.trackingUrl||''}`).join('\n\n')}\n\nPlease reply with any questions.\nTJ Murphy`:
    `${seller?'A print sale has been recorded. Prodigi handles print production and delivery.':'Thank you for collecting my work. Your payment is confirmed.'}\n\nOrder: ${order.id}\n${lines}\n\nArtwork: $${q.base}\nShipping: $${q.shipping}\nTax: $${q.tax}\nTotal paid: $${q.total} USD\n\nShip to:\n${q.address.name}\n${q.address.street1}\n${q.address.street2||''}\n${q.address.city}, ${q.address.state} ${q.address.zip}\n\n${print?'Prints ship from the print lab, separately from any originals. You will receive a shipment update.':'Originals are packed separately.'}${seller?`\nProdigi status: ${print.status}\nProdigi reference: ${print.providerId||print.request.merchantReference}\nQuoted production cost: $${print.quotedProductionCost}\nQuoted print shipping: $${print.quotedShipping}`:''}\nPlease reply with any questions.\n\nTJ Murphy\nhttps://vermillionaurora.com`;
  const mime=[`From: Vermillion Aurora <tj@vermillionaurora.com>`,`To: ${seller?'tj@vermillionaurora.com':q.email}`,
    `Subject: =?UTF-8?B?${encode((order.mode==='sandbox'?'[TEST] ':'')+subject)}?=`,`Message-ID: <cart-${order.id}-${type}@vermillionaurora.com>`,
    'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',encode(body)].join('\r\n');
  const response=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/messages/send',{method:'POST',signal:AbortSignal.timeout(20000),headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({raw:encode(mime).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'')})});
  const result=await response.json();if(!response.ok||!result.id)throw Error('Order email needs review');return result.id;
}
