// Generated by npm run build from catalog/products.json. Do not edit.
export const catalogVersion = "b1917cfc6b59cbc211c6";
export const inventory = {
  "coined-in-watercolor-film-poster": {
    "status": "not-for-sale"
  },
  "el-zonte-at-sunrise": {
    "status": "available"
  },
  "honeybadger-and-cub-with-genesis-block": {
    "status": "available"
  },
  "painting-beach-walk": {
    "status": "sold"
  },
  "painting-chef-in-white": {
    "status": "available"
  },
  "painting-clouds-over-water": {
    "status": "available"
  },
  "painting-couple-in-color": {
    "status": "not-for-sale"
  },
  "painting-embrace": {
    "status": "sold"
  },
  "painting-emergence": {
    "status": "available"
  },
  "painting-family-portrait": {
    "status": "not-for-sale"
  },
  "painting-festival-portrait": {
    "status": "available"
  },
  "painting-figures-in-wheatfield": {
    "status": "sold"
  },
  "painting-golden-coast": {
    "status": "sold"
  },
  "painting-golden-reflection": {
    "status": "not-for-sale"
  },
  "painting-guitarist": {
    "status": "not-for-sale"
  },
  "painting-insect-garden": {
    "status": "available"
  },
  "painting-lightburst": {
    "status": "available"
  },
  "painting-moonlit-water": {
    "status": "available"
  },
  "painting-mount-rainier-at-sunset": {
    "status": "sold"
  },
  "painting-phoenix-rising": {
    "status": "available"
  },
  "painting-portrait-in-blue": {
    "status": "not-for-sale"
  },
  "painting-portrait-in-blue-light": {
    "status": "not-for-sale"
  },
  "painting-portrait-in-gold": {
    "status": "available"
  },
  "painting-portrait-in-green": {
    "status": "available"
  },
  "painting-portrait-with-cheese": {
    "status": "available"
  },
  "painting-portrait-with-hat": {
    "status": "available"
  },
  "painting-portrait-with-scarf": {
    "status": "not-for-sale"
  },
  "painting-red-horizon": {
    "status": "available"
  },
  "painting-shoreline-at-dusk": {
    "status": "available"
  },
  "painting-studio-figure": {
    "status": "available"
  },
  "painting-sunflower-woman": {
    "status": "sold"
  },
  "painting-sunset-reflection": {
    "status": "sold"
  },
  "painting-sunset-shore": {
    "status": "not-for-sale"
  },
  "painting-sunset-silhouette": {
    "status": "sold"
  },
  "painting-twin-dragons": {
    "status": "available"
  },
  "painting-two-soldiers": {
    "status": "not-for-sale"
  },
  "paul-murphy-painting-1": {
    "status": "available"
  },
  "paul-murphy-painting-11": {
    "status": "available"
  },
  "paul-murphy-painting-14": {
    "status": "available"
  },
  "paul-murphy-painting-15": {
    "status": "available"
  },
  "paul-murphy-painting-2": {
    "status": "available"
  },
  "paul-murphy-painting-23": {
    "status": "available"
  },
  "paul-murphy-painting-24": {
    "status": "available"
  },
  "paul-murphy-painting-25": {
    "status": "available"
  },
  "paul-murphy-painting-27": {
    "status": "available"
  },
  "paul-murphy-painting-28": {
    "status": "available"
  },
  "paul-murphy-painting-3": {
    "status": "available"
  },
  "paul-murphy-painting-34": {
    "status": "available"
  },
  "paul-murphy-painting-35": {
    "status": "available"
  },
  "paul-murphy-painting-38": {
    "status": "available"
  },
  "paul-murphy-painting-39": {
    "status": "available"
  },
  "paul-murphy-painting-40": {
    "status": "available"
  },
  "paul-murphy-painting-41": {
    "status": "available"
  },
  "paul-murphy-painting-43": {
    "status": "available"
  },
  "paul-murphy-painting-44": {
    "status": "available"
  },
  "paul-murphy-painting-45": {
    "status": "available"
  },
  "paul-murphy-painting-51": {
    "status": "available"
  },
  "paul-murphy-painting-55": {
    "status": "available"
  },
  "paul-murphy-painting-56": {
    "status": "available"
  },
  "paul-murphy-painting-57": {
    "status": "available"
  },
  "paul-murphy-painting-6": {
    "status": "available"
  },
  "paul-murphy-painting-62": {
    "status": "available"
  },
  "paul-murphy-painting-63": {
    "status": "available"
  },
  "paul-murphy-painting-64": {
    "status": "available"
  },
  "paul-murphy-painting-65": {
    "status": "available"
  },
  "paul-murphy-painting-7": {
    "status": "available"
  },
  "paul-murphy-painting-72": {
    "status": "available"
  },
  "paul-murphy-painting-73": {
    "status": "available"
  },
  "paul-murphy-painting-74": {
    "status": "available"
  },
  "paul-murphy-painting-8": {
    "status": "available"
  },
  "paul-murphy-painting-82": {
    "status": "available"
  },
  "paul-murphy-painting-83": {
    "status": "available"
  },
  "paul-murphy-painting-84": {
    "status": "available"
  },
  "paul-murphy-painting-85": {
    "status": "available"
  },
  "paul-murphy-painting-86": {
    "status": "not-for-sale"
  },
  "warszawska-syrenka": {
    "status": "available"
  }
};
export const legacyLinks = {
  "warszawska-syrenka": {
    "title": "Warszawska Syrenka",
    "amount": "1200.00",
    "currency": "USD",
    "url": "https://www.paypal.com/ncp/payment/T27GYZKUZSYMC"
  }
};
export default {
  "el-zonte-at-sunrise": {
    "title": "El Zonte at Sunrise, El Salvador",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "honeybadger-and-cub-with-genesis-block": {
    "title": "Honeybadger and Cub with Genesis Block",
    "amount": "1200.00",
    "currency": "USD",
    "parcel": {
      "length": 28,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-chef-in-white": {
    "title": "Jimmy Song at Pacific Bitcoin Festival",
    "amount": "400.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-clouds-over-water": {
    "title": "Sunset in Atami, El Salvador",
    "amount": "200.00",
    "currency": "USD",
    "parcel": {
      "length": 8,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-emergence": {
    "title": "El Salvador: Present - Chase Toole Collab",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-festival-portrait": {
    "title": "Wonder",
    "amount": "2000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-insect-garden": {
    "title": "El Salvador: Past - Chase Toole Collab",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-lightburst": {
    "title": "Revelation",
    "amount": "2000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-moonlit-water": {
    "title": "Moonrise in the North Cascades",
    "amount": "600.00",
    "currency": "USD",
    "parcel": {
      "length": 16,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-phoenix-rising": {
    "title": "Achievement",
    "amount": "2000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-portrait-in-gold": {
    "title": "Dorian Nakamoto",
    "amount": "20.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 12,
      "height": 0.125,
      "weight": 0.25
    },
    "packaging": "flat",
    "insuranceRequested": true
  },
  "painting-portrait-in-green": {
    "title": "Chase Toole",
    "amount": "20.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 12,
      "height": 0.125,
      "weight": 0.25
    },
    "packaging": "flat",
    "insuranceRequested": true
  },
  "painting-portrait-with-cheese": {
    "title": "Brekkie Finishing Orange Calcite B",
    "amount": "400.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-portrait-with-hat": {
    "title": "Sunrise on Rainier from Denny Blaine with Eagle Catching Fish",
    "amount": "3000.00",
    "currency": "USD",
    "parcel": {
      "length": 22,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-red-horizon": {
    "title": "Maui Sunset from Kihei",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-shoreline-at-dusk": {
    "title": "El Zonte at Sunrise, El Salvador",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-studio-figure": {
    "title": "Brekkie Hoisting Orange Calcite B",
    "amount": "400.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "painting-twin-dragons": {
    "title": "El Salvador: Future - Chase Toole Collab",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-1": {
    "title": "Tipi",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-11": {
    "title": "Puerto Rico Beach",
    "amount": "50.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-14": {
    "title": "Eagle from photo 1",
    "amount": "75.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-15": {
    "title": "Eagle from photo 2",
    "amount": "75.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-2": {
    "title": "Leo/Bear Constilation",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 38,
      "width": 18,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-23": {
    "title": "My Ego",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-24": {
    "title": "Beach Egland AFB",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 11,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-25": {
    "title": "Spiritual Sedona Mountains 1",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-27": {
    "title": "Spiritual Sedona Mountains 2",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-28": {
    "title": "Spiritual Sedona Mountains 3",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-3": {
    "title": "Rebel Loon/MN ICE Protest",
    "amount": "50.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-34": {
    "title": "Spiritual Sedona Mountains 4",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-35": {
    "title": "Spiritual Sedona Mountains 5",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-38": {
    "title": "Spiritual Sedona Mountains 6",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-39": {
    "title": "Spiritual Sedona Mountains 7",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-40": {
    "title": "Spiritual Sedona Mountains 8",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-41": {
    "title": "Spiritual Sedona Mountains 9",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-43": {
    "title": "Spiritual Sedona Mountains 10",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-44": {
    "title": "Spiritual Sedona Mountains 11",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-45": {
    "title": "Spiritual Sedona Mountains 12",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-51": {
    "title": "Puerto Rico Waterfront",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-56": {
    "title": "Peach Preserves",
    "amount": "600.00",
    "currency": "USD",
    "parcel": {
      "length": 18,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-57": {
    "title": "Lady in Gold",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 38,
      "width": 18,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-6": {
    "title": "Son TJ Sedona",
    "amount": "50.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-62": {
    "title": "Waiting on your ship",
    "amount": "500.00",
    "currency": "USD",
    "parcel": {
      "length": 19,
      "width": 16,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-63": {
    "title": "Slot Canyon Face",
    "amount": "500.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-64": {
    "title": "Slot Canyon Arizona",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-65": {
    "title": "Phoenix",
    "amount": "500.00",
    "currency": "USD",
    "parcel": {
      "length": 10,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-7": {
    "title": "Slot Canyon",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-72": {
    "title": "Dancing Wolf on Moon",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 13,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-73": {
    "title": "Sunset Tree",
    "amount": "50.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-74": {
    "title": "Music Notes of the Universe",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 13,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-8": {
    "title": "Arixona Slot Cave",
    "amount": "100.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-82": {
    "title": "Angies' Eyes",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 13,
      "width": 4,
      "height": 4,
      "weight": 2
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-83": {
    "title": "Soul Connections 1",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 10,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-84": {
    "title": "Soul Connections 2",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 10,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-85": {
    "title": "Soul Connections 3",
    "amount": "25.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 10,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  }
};
