// Generated by npm run build from catalog/products.json. Do not edit.
export const catalogVersion = "330f530f1d94c933abd7";
export const inventory = {
  "coined-in-watercolor-film-poster": {
    "status": "not-for-sale"
  },
  "el-zonte-at-sunrise": {
    "status": "available"
  },
  "honeybadger-and-cub-with-genesis-block": {
    "status": "available"
  },
  "sunset-in-el-tunco-el-salvador": {
    "status": "sold"
  },
  "painting-chef-in-white": {
    "status": "available"
  },
  "painting-clouds-over-water": {
    "status": "available"
  },
  "painting-couple-in-color": {
    "status": "not-for-sale"
  },
  "michael-and-katie-in-yelapa": {
    "status": "sold"
  },
  "painting-emergence": {
    "status": "available"
  },
  "myself-my-mother-ruth-my-grandpa-howard": {
    "status": "not-for-sale"
  },
  "painting-festival-portrait": {
    "status": "not-for-sale"
  },
  "painting-figures-in-wheatfield": {
    "status": "sold"
  },
  "painting-golden-coast": {
    "status": "sold"
  },
  "sunset-in-el-zonte-el-salvador": {
    "status": "not-for-sale"
  },
  "painting-guitarist": {
    "status": "not-for-sale"
  },
  "painting-insect-garden": {
    "status": "available"
  },
  "painting-lightburst": {
    "status": "not-for-sale"
  },
  "painting-moonlit-water": {
    "status": "available"
  },
  "girl-wearing-flower-crown": {
    "status": "sold"
  },
  "painting-phoenix-rising": {
    "status": "not-for-sale"
  },
  "grandpa-howard": {
    "status": "not-for-sale"
  },
  "painting-portrait-in-blue-light": {
    "status": "not-for-sale"
  },
  "painting-portrait-in-gold": {
    "status": "available"
  },
  "painting-portrait-in-green": {
    "status": "available"
  },
  "painting-portrait-with-cheese": {
    "status": "available"
  },
  "painting-portrait-with-hat": {
    "status": "not-for-sale"
  },
  "painting-portrait-with-scarf": {
    "status": "not-for-sale"
  },
  "painting-red-horizon": {
    "status": "available"
  },
  "hope-the-vermillion-aurora": {
    "status": "available"
  },
  "painting-shoreline-at-dusk": {
    "status": "available"
  },
  "el-zonte-before-dawn": {
    "status": "available"
  },
  "sunrise-in-el-zonte-large": {
    "status": "available"
  },
  "meditation-at-denny-blaine": {
    "status": "available"
  },
  "painting-studio-figure": {
    "status": "available"
  },
  "painting-sunflower-woman": {
    "status": "sold"
  },
  "joaquim-in-zihuatanejo": {
    "status": "sold"
  },
  "daniel-portrait-1": {
    "status": "not-for-sale"
  },
  "painting-sunset-silhouette": {
    "status": "sold"
  },
  "painting-twin-dragons": {
    "status": "available"
  },
  "rice-paddies-in-vietnam": {
    "status": "not-for-sale"
  },
  "paul-murphy-painting-1": {
    "status": "available"
  },
  "paul-murphy-painting-11": {
    "status": "available"
  },
  "paul-murphy-painting-14": {
    "status": "available"
  },
  "paul-murphy-painting-15": {
    "status": "available"
  },
  "paul-murphy-painting-2": {
    "status": "available"
  },
  "paul-murphy-painting-23": {
    "status": "available"
  },
  "paul-murphy-painting-24": {
    "status": "available"
  },
  "paul-murphy-painting-25": {
    "status": "available"
  },
  "paul-murphy-painting-27": {
    "status": "available"
  },
  "paul-murphy-painting-28": {
    "status": "available"
  },
  "paul-murphy-painting-3": {
    "status": "available"
  },
  "paul-murphy-painting-34": {
    "status": "available"
  },
  "paul-murphy-painting-35": {
    "status": "available"
  },
  "paul-murphy-painting-38": {
    "status": "available"
  },
  "paul-murphy-painting-39": {
    "status": "available"
  },
  "paul-murphy-painting-40": {
    "status": "available"
  },
  "paul-murphy-painting-41": {
    "status": "available"
  },
  "paul-murphy-painting-43": {
    "status": "available"
  },
  "paul-murphy-painting-44": {
    "status": "available"
  },
  "paul-murphy-painting-45": {
    "status": "available"
  },
  "paul-murphy-painting-51": {
    "status": "available"
  },
  "paul-murphy-painting-55": {
    "status": "available"
  },
  "paul-murphy-painting-56": {
    "status": "available"
  },
  "paul-murphy-painting-57": {
    "status": "available"
  },
  "paul-murphy-painting-6": {
    "status": "available"
  },
  "paul-murphy-painting-62": {
    "status": "available"
  },
  "paul-murphy-painting-63": {
    "status": "available"
  },
  "paul-murphy-painting-64": {
    "status": "available"
  },
  "paul-murphy-painting-65": {
    "status": "available"
  },
  "paul-murphy-painting-7": {
    "status": "available"
  },
  "paul-murphy-painting-72": {
    "status": "available"
  },
  "paul-murphy-painting-73": {
    "status": "available"
  },
  "paul-murphy-painting-74": {
    "status": "available"
  },
  "paul-murphy-painting-8": {
    "status": "available"
  },
  "paul-murphy-painting-83": {
    "status": "available"
  },
  "paul-murphy-painting-84": {
    "status": "available"
  },
  "paul-murphy-painting-85": {
    "status": "available"
  },
  "paul-murphy-painting-86": {
    "status": "not-for-sale"
  },
  "warszawska-syrenka": {
    "status": "available"
  },
  "burning-man-temple-2022-blue": {
    "status": "not-for-sale"
  },
  "burning-man-temple-2022-pink": {
    "status": "not-for-sale"
  },
  "burning-man-temple-2022-flame": {
    "status": "not-for-sale"
  },
  "burning-man-temple-2022-daytime": {
    "status": "not-for-sale"
  },
  "cormorant-presiding-over-sunset-on-puget-sound": {
    "status": "not-for-sale"
  },
  "book-art-66fa2eb4ccbaa13b172e": {
    "status": "not-for-sale"
  },
  "book-art-ded6b759e667e3c2a313": {
    "status": "not-for-sale"
  },
  "book-art-e6068e265bfdc379526c": {
    "status": "not-for-sale"
  },
  "book-art-9ae261289a3bce952c6f": {
    "status": "not-for-sale"
  },
  "book-art-2a670ca4f87a8cbd8b02": {
    "status": "not-for-sale"
  },
  "book-art-d78badff7e21472c00b8": {
    "status": "not-for-sale"
  },
  "book-art-deb3358c321671dae1fc": {
    "status": "not-for-sale"
  },
  "book-art-85d951d0a1ea09ef4aa6": {
    "status": "not-for-sale"
  },
  "book-art-502372c530af5261540c": {
    "status": "not-for-sale"
  },
  "book-art-164f60d23032b0f718de": {
    "status": "not-for-sale"
  },
  "book-art-aa4dcced8a2ae6a8111c": {
    "status": "not-for-sale"
  },
  "book-art-8fde7c978d6cd5d53727": {
    "status": "not-for-sale"
  },
  "book-art-5e4eb881d89ae9f5c635": {
    "status": "not-for-sale"
  },
  "book-art-f56007f6a7d6ee955caf": {
    "status": "not-for-sale"
  },
  "book-art-d1399111a441ed91feaa": {
    "status": "not-for-sale"
  },
  "book-art-c198f09bc8ddad18ed1e": {
    "status": "not-for-sale"
  },
  "book-art-9a4b9331f62350fa36fc": {
    "status": "not-for-sale"
  },
  "book-art-b01b8695b2528cb850a3": {
    "status": "not-for-sale"
  },
  "book-art-164299ae97e7b62137f5": {
    "status": "not-for-sale"
  },
  "book-art-7a3ad7bacdb71faac1b8": {
    "status": "not-for-sale"
  },
  "book-art-9c7b9d41bee5615f1d7f": {
    "status": "not-for-sale"
  },
  "book-art-87cf2a732259b313f5ab": {
    "status": "not-for-sale"
  },
  "book-art-93957f4169bc931e0a52": {
    "status": "not-for-sale"
  },
  "book-art-c4a5109c84daedd78291": {
    "status": "not-for-sale"
  },
  "book-art-471daf14a8bb7883f114": {
    "status": "not-for-sale"
  },
  "book-art-ac338ff3806b66917b3c": {
    "status": "not-for-sale"
  },
  "book-art-7599e02b4ff7013e7261": {
    "status": "not-for-sale"
  },
  "book-art-1cc00425e5226b3aa20c": {
    "status": "not-for-sale"
  },
  "book-art-9b6b4f1ce8b283e14b21": {
    "status": "not-for-sale"
  },
  "book-art-7676696646b77fc3ca94": {
    "status": "not-for-sale"
  },
  "book-art-e6f013fae1925ab77100": {
    "status": "not-for-sale"
  },
  "book-art-c8da7882b2a3b7a36874": {
    "status": "not-for-sale"
  },
  "book-art-103c2ba59ca485e56a86": {
    "status": "not-for-sale"
  },
  "book-art-fc89b36cb40743a90fa8": {
    "status": "not-for-sale"
  },
  "book-art-e3293c73dbb01f94b39b": {
    "status": "not-for-sale"
  },
  "book-art-a2e53a8418a8d84f3dc5": {
    "status": "not-for-sale"
  },
  "book-art-56e40e02275a8767a802": {
    "status": "not-for-sale"
  },
  "book-art-fe853b565936ef8b2e73": {
    "status": "not-for-sale"
  },
  "book-art-f7e73a57e2af01359446": {
    "status": "not-for-sale"
  },
  "book-art-9f546bff5102042a3ad4": {
    "status": "not-for-sale"
  },
  "book-art-9fc2e730b10c7b8c333b": {
    "status": "not-for-sale"
  },
  "book-art-27fee33e69f262ecfacb": {
    "status": "not-for-sale"
  },
  "book-art-65bf0ecd265f1fd96e4a": {
    "status": "not-for-sale"
  },
  "book-art-ff6db6906f0ed48ccc3a": {
    "status": "not-for-sale"
  },
  "book-art-55829535637cd4974a88": {
    "status": "not-for-sale"
  },
  "book-art-04a049ea60a5a09e6873": {
    "status": "not-for-sale"
  },
  "book-art-e589c9375e23d1de4748": {
    "status": "not-for-sale"
  },
  "book-art-f2025e5a72f4a70866c6": {
    "status": "not-for-sale"
  },
  "book-art-9f6386bac0e6198f6661": {
    "status": "not-for-sale"
  },
  "book-art-82ab8d65fb50fe0d096a": {
    "status": "not-for-sale"
  },
  "book-art-04de39dfa1817b8d1ed9": {
    "status": "not-for-sale"
  },
  "book-art-06b4b66f6389416c412c": {
    "status": "not-for-sale"
  },
  "book-art-94e2edf9a24c90950489": {
    "status": "not-for-sale"
  },
  "book-art-6e6d7ac51608e0b7f10f": {
    "status": "not-for-sale"
  },
  "book-art-e97329411fa8b273b508": {
    "status": "not-for-sale"
  },
  "book-art-f91504eaa0ab6b936c29": {
    "status": "not-for-sale"
  },
  "book-art-fb5eaeb2078ebf9c75f0": {
    "status": "not-for-sale"
  },
  "book-art-4bb692457bed7cd4bb00": {
    "status": "not-for-sale"
  },
  "book-art-024a1e2da99a49b4438a": {
    "status": "not-for-sale"
  },
  "book-art-02b06cbfebb63c2794d9": {
    "status": "not-for-sale"
  },
  "book-art-311b1c39d98767f359b5": {
    "status": "not-for-sale"
  },
  "book-art-cb92d1d647c6f92403c7": {
    "status": "not-for-sale"
  },
  "book-art-64a80ece808ac08d4877": {
    "status": "not-for-sale"
  },
  "book-art-2136f2260225dd8ef20a": {
    "status": "not-for-sale"
  },
  "book-art-29b3572972c367d351d1": {
    "status": "not-for-sale"
  },
  "book-art-8ff9ac182d32fa228450": {
    "status": "not-for-sale"
  },
  "book-art-b7a9cd259d8ac51a236b": {
    "status": "not-for-sale"
  },
  "book-art-c33709aeb2717b0c53de": {
    "status": "not-for-sale"
  },
  "book-art-76b81da2337321bf158d": {
    "status": "not-for-sale"
  },
  "book-art-ccff23f1e469654faa05": {
    "status": "not-for-sale"
  },
  "book-art-9c77e540218eab97ba3d": {
    "status": "not-for-sale"
  },
  "book-art-a137dffe65723d0b5a07": {
    "status": "not-for-sale"
  },
  "book-art-7df006b029abcb751da2": {
    "status": "not-for-sale"
  },
  "book-art-d1a4ee225dafe10ba934": {
    "status": "not-for-sale"
  },
  "book-art-db933efcbc4fbe01c841": {
    "status": "not-for-sale"
  },
  "book-art-8137549f4fe7a3a1b90d": {
    "status": "not-for-sale"
  },
  "book-art-edbfc2a7fff1189141f6": {
    "status": "not-for-sale"
  },
  "book-art-4bf5a04e40e7d8341378": {
    "status": "not-for-sale"
  },
  "book-art-74a736000a32427842b1": {
    "status": "not-for-sale"
  },
  "book-art-9209f1fd7d47f373597f": {
    "status": "not-for-sale"
  },
  "book-art-a61c71e5de8cc1b71500": {
    "status": "not-for-sale"
  },
  "book-art-596837cb5ff533c620dd": {
    "status": "not-for-sale"
  },
  "book-art-7bce6e3509027d1f7a0b": {
    "status": "not-for-sale"
  },
  "book-art-b50262c37f44843487ae": {
    "status": "not-for-sale"
  },
  "book-art-92fdb3112257f4fb66e8": {
    "status": "not-for-sale"
  },
  "book-art-3a9cba708a8045364e82": {
    "status": "not-for-sale"
  },
  "book-art-6bcf18417734a8e3010a": {
    "status": "not-for-sale"
  },
  "book-art-0d7df713c5f0f67733ae": {
    "status": "not-for-sale"
  },
  "book-art-0c4b161071524e23d519": {
    "status": "not-for-sale"
  },
  "book-art-b7410a9f4340e559e4f4": {
    "status": "not-for-sale"
  },
  "book-art-1143b08e177333e43dc7": {
    "status": "not-for-sale"
  },
  "book-art-18e4d05240ce63a1a44b": {
    "status": "not-for-sale"
  },
  "book-art-64cfd389b3dbb5cde532": {
    "status": "not-for-sale"
  },
  "book-art-1708a7dca996aca40e6c": {
    "status": "not-for-sale"
  },
  "book-art-a627c7b7d19ace6b3e51": {
    "status": "not-for-sale"
  },
  "book-art-0e4564564eee5d70c105": {
    "status": "not-for-sale"
  },
  "book-art-44161b6b117af79e3df4": {
    "status": "not-for-sale"
  },
  "book-art-029f45a5fbfd6c90212e": {
    "status": "not-for-sale"
  },
  "book-art-28bec44600b36ed0766f": {
    "status": "not-for-sale"
  },
  "book-art-ad30c3da712401606ea6": {
    "status": "not-for-sale"
  },
  "book-art-7123da0440d527299914": {
    "status": "not-for-sale"
  },
  "book-art-14d2876a55c720cbc908": {
    "status": "not-for-sale"
  },
  "book-art-c347459aa3f77f7213ae": {
    "status": "not-for-sale"
  },
  "book-art-159503a8e82d7b91c293": {
    "status": "not-for-sale"
  },
  "book-art-4a03ad4df3ef51a39639": {
    "status": "not-for-sale"
  },
  "book-art-616ff8378f27047b4a91": {
    "status": "not-for-sale"
  },
  "book-art-1ff2691533c9a9d8b091": {
    "status": "not-for-sale"
  },
  "book-art-37fe572d9bb47cab3bc7": {
    "status": "not-for-sale"
  },
  "book-art-3cd6b3fb3e356c4b1d1d": {
    "status": "not-for-sale"
  },
  "book-art-04f4a52773ffd19b4f67": {
    "status": "not-for-sale"
  },
  "book-art-614d5b68dbe5052e302a": {
    "status": "not-for-sale"
  },
  "book-art-54ff45104a57a68d4beb": {
    "status": "not-for-sale"
  },
  "book-art-4350a257e5a6a5e75a31": {
    "status": "not-for-sale"
  },
  "book-art-f367882aaeb0e32471eb": {
    "status": "not-for-sale"
  },
  "book-art-67cc9a4d5823eca2182e": {
    "status": "not-for-sale"
  },
  "book-art-df8db0bc08adfeae5829": {
    "status": "not-for-sale"
  },
  "book-art-8d1545e1ac13c99eb4ce": {
    "status": "not-for-sale"
  },
  "book-art-ea6e156a9a533d06f198": {
    "status": "not-for-sale"
  },
  "book-art-1a843fe4506374e2f33e": {
    "status": "not-for-sale"
  },
  "book-art-5cdcafbf4759d14a793f": {
    "status": "not-for-sale"
  },
  "book-art-466dc684227286c40502": {
    "status": "not-for-sale"
  },
  "book-art-a526883c6ca5fefe7402": {
    "status": "not-for-sale"
  },
  "book-art-82127d1886ae57d5cb6e": {
    "status": "not-for-sale"
  },
  "book-art-0a80f9a5da0d39edc80f": {
    "status": "not-for-sale"
  },
  "book-art-0351c2ff290526e4f204": {
    "status": "not-for-sale"
  },
  "book-art-7a498f39e7a66a2e8eb5": {
    "status": "not-for-sale"
  },
  "book-art-e1fa746bb51029294a17": {
    "status": "not-for-sale"
  },
  "book-art-c04c7e48687fe35e65f5": {
    "status": "not-for-sale"
  },
  "book-art-d6e03f6907615dac3797": {
    "status": "not-for-sale"
  },
  "book-art-ec22daff29e72f16eb76": {
    "status": "not-for-sale"
  },
  "book-art-43a3f16ac35df7262254": {
    "status": "not-for-sale"
  },
  "book-art-e4bbfe556c3c847d9c90": {
    "status": "not-for-sale"
  },
  "book-art-0735a5fb0eb1c613b658": {
    "status": "not-for-sale"
  },
  "book-art-6ef848d3ccb6b48184ab": {
    "status": "not-for-sale"
  },
  "book-art-044d157c01c7bb07eeab": {
    "status": "not-for-sale"
  },
  "book-art-4d53927ad111f0259402": {
    "status": "not-for-sale"
  },
  "book-art-4afb5cab4bdbe1ff6845": {
    "status": "not-for-sale"
  },
  "book-art-b57fc2205e7bce68d524": {
    "status": "not-for-sale"
  },
  "book-art-b38b9ae1893908d604da": {
    "status": "not-for-sale"
  },
  "book-art-1fb8762b7bf8fce0d0f9": {
    "status": "not-for-sale"
  },
  "book-art-7718008765132b8bc17f": {
    "status": "not-for-sale"
  },
  "book-art-ef24f49017a62819330d": {
    "status": "not-for-sale"
  },
  "book-art-504e3fafdacd7c9bbcd0": {
    "status": "not-for-sale"
  },
  "book-art-4a0bb9cdd6c404c4e77c": {
    "status": "not-for-sale"
  },
  "book-art-0ee2717bc04e65d0507e": {
    "status": "not-for-sale"
  },
  "book-art-deb92de6e72f7b3ce951": {
    "status": "not-for-sale"
  },
  "book-art-a26ad79970ed645ce1a9": {
    "status": "not-for-sale"
  },
  "book-art-5a462e9705ba39d756a2": {
    "status": "not-for-sale"
  },
  "book-art-d95085ce3029e490bb31": {
    "status": "not-for-sale"
  },
  "book-art-481025eb48c792356553": {
    "status": "not-for-sale"
  },
  "book-art-3cd168e82a87b1ccf91b": {
    "status": "not-for-sale"
  },
  "book-art-1d0517e85d349222c362": {
    "status": "not-for-sale"
  },
  "book-art-a6a2c048812a41cee4e4": {
    "status": "not-for-sale"
  },
  "book-art-0f696788184bbba1d236": {
    "status": "not-for-sale"
  },
  "book-art-50a7984f819bec72d1c7": {
    "status": "not-for-sale"
  },
  "book-art-4c6fb3817fed4e5a6195": {
    "status": "not-for-sale"
  },
  "book-art-19d9a8360c1f1df745d6": {
    "status": "not-for-sale"
  },
  "book-art-ffffb682294d4b12c35e": {
    "status": "not-for-sale"
  },
  "book-art-bab6791e6223d24b9fbd": {
    "status": "not-for-sale"
  }
};
export const legacyLinks = {};
export default {
  "el-zonte-at-sunrise": {
    "title": "Sunrise from Punta El Zonte Hostel",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 1.625
    },
    "packaging": "tube"
  },
  "honeybadger-and-cub-with-genesis-block": {
    "title": "Honeybadger and Cub with Genesis Block",
    "amount": "1200.00",
    "currency": "USD",
    "parcel": {
      "length": 28,
      "width": 4,
      "height": 4,
      "weight": 1.8125
    },
    "packaging": "tube"
  },
  "painting-chef-in-white": {
    "title": "Jimmy Song @jimmysong",
    "amount": "400.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 4,
      "height": 4,
      "weight": 0.875
    },
    "packaging": "tube"
  },
  "painting-clouds-over-water": {
    "title": "El Salvador",
    "amount": "200.00",
    "currency": "USD",
    "parcel": {
      "length": 8,
      "width": 4,
      "height": 4,
      "weight": 0.4375
    },
    "packaging": "tube"
  },
  "painting-emergence": {
    "title": "El Salvador: Present - Chase Toole Collab",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 1.625
    },
    "packaging": "tube"
  },
  "painting-insect-garden": {
    "title": "El Salvador: Past - Chase Toole Collab",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 1.625
    },
    "packaging": "tube"
  },
  "painting-moonlit-water": {
    "title": "Moonrise Over the Cascades",
    "amount": "500.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 4,
      "height": 4,
      "weight": 0.5625
    },
    "packaging": "tube"
  },
  "painting-portrait-in-gold": {
    "title": "Dorian Nakamoto",
    "amount": "200.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 12,
      "height": 0.125,
      "weight": 0.25
    },
    "packaging": "flat",
    "insuranceRequested": true
  },
  "painting-portrait-in-green": {
    "title": "Chase Toole",
    "amount": "200.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 12,
      "height": 0.125,
      "weight": 0.25
    },
    "packaging": "flat",
    "insuranceRequested": true
  },
  "painting-portrait-with-cheese": {
    "title": "Brekkie @BVBTC with polished Bitcoin B",
    "amount": "400.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 4,
      "height": 4,
      "weight": 0.875
    },
    "packaging": "tube"
  },
  "painting-red-horizon": {
    "title": "Sunset at Kihei on Maui",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 23,
      "width": 4,
      "height": 4,
      "weight": 1.5
    },
    "packaging": "tube"
  },
  "hope-the-vermillion-aurora": {
    "title": "Hope, the Vermillion Aurora",
    "amount": "2000.00",
    "currency": "USD",
    "parcel": {
      "length": 22,
      "width": 4,
      "height": 4,
      "weight": 1.4375
    },
    "packaging": "tube"
  },
  "painting-shoreline-at-dusk": {
    "title": "El Zonte at Dawn",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 1.625
    },
    "packaging": "tube"
  },
  "el-zonte-before-dawn": {
    "title": "El Zonte Before Dawn",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 1.625
    },
    "packaging": "tube"
  },
  "sunrise-in-el-zonte-large": {
    "title": "Sunrise in El Zonte (Large)",
    "amount": "2000.00",
    "currency": "USD",
    "parcel": {
      "length": 36,
      "width": 4,
      "height": 4,
      "weight": 2.4375
    },
    "packaging": "tube"
  },
  "meditation-at-denny-blaine": {
    "title": "Meditation at Denny Blaine",
    "amount": "600.00",
    "currency": "USD",
    "parcel": {
      "length": 16,
      "width": 4,
      "height": 4,
      "weight": 0.875
    },
    "packaging": "tube"
  },
  "painting-studio-figure": {
    "title": "Brekkie @BVBTC hoisting a sculpture in progress",
    "amount": "400.00",
    "currency": "USD",
    "parcel": {
      "length": 15,
      "width": 4,
      "height": 4,
      "weight": 0.875
    },
    "packaging": "tube"
  },
  "painting-twin-dragons": {
    "title": "El Salvador: Future - Chase Toole Collab",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 24,
      "width": 4,
      "height": 4,
      "weight": 1.625
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-1": {
    "title": "Tipi",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-11": {
    "title": "Puerto Rico Beach",
    "amount": "250.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 4,
      "height": 4,
      "weight": 0.5
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-14": {
    "title": "Eagle from Photo 1",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-15": {
    "title": "Eagle from Photo 2",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-2": {
    "title": "Leo/Bear Constellation",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 38,
      "width": 18,
      "height": 2,
      "weight": 6
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-23": {
    "title": "My Ego",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-24": {
    "title": "Beach Eglin AFB",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 11,
      "width": 4,
      "height": 4,
      "weight": 0.5
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-25": {
    "title": "Spiritual Sedona Mountains 1",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-27": {
    "title": "Spiritual Sedona Mountains 2",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-28": {
    "title": "Spiritual Sedona Mountains 3",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-3": {
    "title": "Rebel Loon/MN ICE Protest",
    "amount": "250.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-34": {
    "title": "Spiritual Sedona Mountains 4",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-35": {
    "title": "Spiritual Sedona Mountains 5",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-38": {
    "title": "Spiritual Sedona Mountains 6",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-39": {
    "title": "Spiritual Sedona Mountains 7",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-40": {
    "title": "Spiritual Sedona Mountains 8",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-41": {
    "title": "Spiritual Sedona Mountains 9",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-43": {
    "title": "Spiritual Sedona Mountains 10",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-44": {
    "title": "Spiritual Sedona Mountains 11",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-45": {
    "title": "Spiritual Sedona Mountains 12",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-51": {
    "title": "Puerto Rico Waterfront",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-55": {
    "title": "Pyramid from Photo",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-56": {
    "title": "Peach Preserves",
    "amount": "600.00",
    "currency": "USD",
    "parcel": {
      "length": 18,
      "width": 4,
      "height": 4,
      "weight": 0.875
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-57": {
    "title": "Lady in Gold",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 38,
      "width": 18,
      "height": 2,
      "weight": 6
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-6": {
    "title": "Son TJ Sedona",
    "amount": "250.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-62": {
    "title": "Waiting on Your Ship",
    "amount": "500.00",
    "currency": "USD",
    "parcel": {
      "length": 19,
      "width": 16,
      "height": 2,
      "weight": 3
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-63": {
    "title": "Slot Canyon Face",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-64": {
    "title": "Slot Canyon Arizona",
    "amount": "1000.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 2
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-65": {
    "title": "Phoenix",
    "amount": "500.00",
    "currency": "USD",
    "parcel": {
      "length": 10,
      "width": 4,
      "height": 4,
      "weight": 0.4375
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-7": {
    "title": "Slot Canyon",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-72": {
    "title": "Dancing Wolf on Moon",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 13,
      "width": 4,
      "height": 4,
      "weight": 0.8125
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-73": {
    "title": "Sunset Tree",
    "amount": "250.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-74": {
    "title": "Music Notes of the Universe",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 13,
      "width": 4,
      "height": 4,
      "weight": 0.75
    },
    "packaging": "tube"
  },
  "paul-murphy-painting-8": {
    "title": "Arizona Slot Cave",
    "amount": "300.00",
    "currency": "USD",
    "parcel": {
      "length": 14,
      "width": 12,
      "height": 2,
      "weight": 0.4375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-83": {
    "title": "Soul Connections 1",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 10,
      "height": 2,
      "weight": 0.375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-84": {
    "title": "Soul Connections 2",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 10,
      "height": 2,
      "weight": 0.375
    },
    "packaging": "flat"
  },
  "paul-murphy-painting-85": {
    "title": "Soul Connections 3",
    "amount": "150.00",
    "currency": "USD",
    "parcel": {
      "length": 12,
      "width": 10,
      "height": 2,
      "weight": 0.375
    },
    "packaging": "flat"
  },
  "warszawska-syrenka": {
    "title": "Warszawska Syrenka",
    "amount": "1200.00",
    "currency": "USD",
    "parcel": {
      "length": 28,
      "width": 4,
      "height": 4,
      "weight": 1.8125
    },
    "packaging": "tube"
  }
};
